Repository gnars-dao/gnars-frontend, pull requests merged in 2024-08, with the labels that each got.

#35 Goldsky base subgraph
  packages/base-subgraph/.gitignore
  packages/base-subgraph/README.md
  packages/base-subgraph/abis/Auction.json
  packages/base-subgraph/abis/Governor.json
  packages/base-subgraph/abis/Manager.json
  packages/base-subgraph/abis/MetadataRendererBase.json
  packages/base-subgraph/abis/MetadataRendererV1.json
  packages/base-subgraph/abis/Token.json
  packages/base-subgraph/abis/Treasury.json
  packages/base-subgraph/config/base.json
  packages/base-subgraph/package.json
  packages/base-subgraph/schema.graphql
  packages/base-subgraph/src/auction.ts
  packages/base-subgraph/src/governor.ts
  packages/base-subgraph/src/manager.ts
  packages/base-subgraph/src/metadata.ts
  packages/base-subgraph/src/token.ts
  packages/base-subgraph/src/utils/createMetadataRendererTemplate.ts
  packages/base-subgraph/src/utils/setTokenMetadata.ts
  packages/base-subgraph/subgraph.yaml.mustache
  packages/base-subgraph/tsconfig.json
  packages/subgraph/README.md
  pnpm-lock.yaml
Labels: bug, current scope

#34 fix GnarInfo text color
  packages/webapp/components/Auction/GnarInfo.tsx
Labels: bug

#53 feat(discord): add discord to top nav, center styled base jump alert
  packages/webapp/components/BaseJumpAnnouncement.tsx
  packages/webapp/components/Explainer.tsx
  packages/webapp/components/Footer.tsx
  packages/webapp/components/Menu.tsx
  pnpm-lock.yaml
Labels: enhancement
